AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Aligno skill normalization Lambda (daily run).

Parameters:
  DatabaseUrl:
    Type: String
    Default: ""
    NoEcho: true
    Description: PostgreSQL connection string (postgresql://user:pass@host:5432/db) or leave empty to use AWS_DB_* vars.
  AwsRegion:
    Type: String
    Default: eu-central-1
    Description: AWS region for Bedrock and Lambda.
  ScraperRoleArn:
    Type: String
    Default: ""
    Description: "(Optional) ARN of the role that runs the scraper (e.g. Fargate task role). If set, that role is allowed to invoke this Lambda so normalization runs after scrape completes."
  ScheduleEnabled:
    Type: String
    Default: "false"
    AllowedValues: [ "true", "false" ]
    Description: "Enable fallback EventBridge schedule (2 AM UTC). Prefer triggering from scraper via NORMALIZE_LAMBDA_NAME when scrape completes."

Globals:
  Function:
    Timeout: 900
    MemorySize: 512
    Runtime: python3.11
    Architectures: [ x86_64 ]

Resources:
  NormalizeSkillsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: aligno-normalize-deps
      ContentUri: layer/
      CompatibleRuntimes:
        - python3.11
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: python3.11

  NormalizeSkillsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: aligno-normalize-skills
      CodeUri: ../src
      Handler: atlas.lambda_handler.handler
      Layers:
        - !Ref NormalizeSkillsLayer
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseUrl
      # AWS_REGION is set automatically by Lambda; AwsRegion is only used in parameters (Schedule etc.)
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: "*"
      Events:
        DailySchedule:
          Type: Schedule
          Properties:
            Schedule: cron(0 2 * * ? *)
            Enabled: !If [ ScheduleEnabled, true, false ]
            Description: Run skill normalization daily at 2 AM UTC

  # Allow scraper role (e.g. Fargate task) to invoke Lambda when scrape completes
  NormalizeInvokePermission:
    Type: AWS::Lambda::Permission
    Condition: HasScraperRole
    Properties:
      FunctionName: !Ref NormalizeSkillsFunction
      Action: lambda:InvokeFunction
      Principal: !Ref ScraperRoleArn

Conditions:
  ScheduleEnabled: !Equals [ !Ref ScheduleEnabled, "true" ]
  HasScraperRole: !Not [ !Equals [ !Ref ScraperRoleArn, "" ] ]

Outputs:
  NormalizeSkillsArn:
    Description: ARN of the normalization Lambda
    Value: !GetAtt NormalizeSkillsFunction.Arn
  NormalizeSkillsName:
    Description: Function name for manual invoke
    Value: !Ref NormalizeSkillsFunction
